/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bhanuka
 */
public class Quality_assurance_form extends javax.swing.JFrame {

    /**
     * Creates new form Quality_assurance_form
     */
    public Quality_assurance_form() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //Are you Srilankan Or Foreigner
        ButtonGroup aa = new ButtonGroup();
        aa.add(jRadioButton_sl);
        aa.add(jRadioButton_fr);
        
        //Is This Your First Visit or Not
        ButtonGroup bb = new ButtonGroup();
        bb.add(jRadioButton_yes);
        bb.add(jRadioButton_no);
        
        //How Long Do You Stay In Our Hotel
        
        ButtonGroup cc = new ButtonGroup();
        cc.add(jRadioButton_2to4);
        cc.add(jRadioButton_5ormore);
        cc.add(jRadioButton_onlyone);
        //How Did Our Front Office Staff Behare During Your Stay
        ButtonGroup dd = new ButtonGroup();
        dd.add(jRadioButton_fse);
        dd.add(jRadioButton_fsg);
        dd.add(jRadioButtonfsp);
        dd.add(jRadioButton_fsf);
        
        //How About the Overall Cleanliness Our Hotel
        ButtonGroup ee = new ButtonGroup();
        ee.add(jRadioButton_oce);
        ee.add(jRadioButton_ocg);
        ee.add(jRadioButton_ocf);
        ee.add(jRadioButton_ocp);
        
        //How About The Cleanlines Of Your Room
        ButtonGroup ff = new ButtonGroup();
        ff.add(jRadioButton1_rce);
        ff.add(jRadioButton_rcg);
        ff.add(jRadioButton_rcf);
        ff.add(jRadioButton_rcp);
        
        //How About The Resturant Foods From Our Hotel
        ButtonGroup gg = new ButtonGroup();
        gg.add(jRadioButton_rfe);
        gg.add(jRadioButton_rff);
        gg.add(jRadioButton_rfg);
        gg.add(jRadioButton_rfp);
        
        //overoll rating
        ButtonGroup hh = new ButtonGroup();
        hh.add(jRadioButton_ore);
        hh.add(jRadioButton_orf);
        hh.add(jRadioButton_org);
        hh.add(jRadioButton_orp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_submite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_fr = new javax.swing.JRadioButton();
        jRadioButton_sl = new javax.swing.JRadioButton();
        jRadioButton_org = new javax.swing.JRadioButton();
        jRadioButton_orf = new javax.swing.JRadioButton();
        jRadioButton_orp = new javax.swing.JRadioButton();
        jRadioButton_ore = new javax.swing.JRadioButton();
        jRadioButton_yes = new javax.swing.JRadioButton();
        jRadioButton_no = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_onlyone = new javax.swing.JRadioButton();
        jRadioButton_2to4 = new javax.swing.JRadioButton();
        jRadioButton_5ormore = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton_fse = new javax.swing.JRadioButton();
        jRadioButtonfsp = new javax.swing.JRadioButton();
        jRadioButton_fsg = new javax.swing.JRadioButton();
        jRadioButton_rfp = new javax.swing.JRadioButton();
        jRadioButton_oce = new javax.swing.JRadioButton();
        jRadioButton_ocp = new javax.swing.JRadioButton();
        jRadioButton_ocg = new javax.swing.JRadioButton();
        jRadioButton_ocf = new javax.swing.JRadioButton();
        jRadioButton1_rce = new javax.swing.JRadioButton();
        jRadioButton_rcg = new javax.swing.JRadioButton();
        jRadioButton_rcf = new javax.swing.JRadioButton();
        jRadioButton_rcp = new javax.swing.JRadioButton();
        jRadioButton_rfe = new javax.swing.JRadioButton();
        jRadioButton_rff = new javax.swing.JRadioButton();
        jRadioButton_rfg = new javax.swing.JRadioButton();
        jRadioButton_fsf = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_about = new javax.swing.JTextArea();
        jTextField_name = new javax.swing.JTextField();
        jButton_logout1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hotel ABC");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Rate Us");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jButton_submite.setBackground(new java.awt.Color(0, 0, 153));
        jButton_submite.setForeground(new java.awt.Color(255, 255, 255));
        jButton_submite.setText("Submite");
        jButton_submite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submiteActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Are you Srilankan or Foreigner");

        jLabel5.setText("Is this your first visit or not");

        jLabel6.setText("Overall rating");

        jRadioButton_fr.setText("Foreigner");
        jRadioButton_fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_frActionPerformed(evt);
            }
        });

        jRadioButton_sl.setSelected(true);
        jRadioButton_sl.setText("Sri Lankan");
        jRadioButton_sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_slActionPerformed(evt);
            }
        });

        jRadioButton_ore.setSelected(true);

        jRadioButton_yes.setSelected(true);
        jRadioButton_yes.setText("yes");
        jRadioButton_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_yesActionPerformed(evt);
            }
        });

        jRadioButton_no.setText("No");

        jLabel8.setText("How long do you stay in our hotel");

        jRadioButton_onlyone.setSelected(true);
        jRadioButton_onlyone.setText("Only One");

        jRadioButton_2to4.setText("2 To 4");

        jRadioButton_5ormore.setText("5 Or More");
        jRadioButton_5ormore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_5ormoreActionPerformed(evt);
            }
        });

        jLabel9.setText("Excellent");

        jLabel10.setText("Good");

        jLabel11.setText("Fair");

        jLabel12.setText("Poor");

        jLabel13.setText("How did our front office staff behafe during your stay");

        jLabel14.setText("How about the overall cleanliness our hotel");

        jLabel15.setText("How about the cleanlines of your room");

        jLabel16.setText("How about the resturant foods from our hotel");

        jRadioButton_fse.setSelected(true);

        jRadioButton_oce.setSelected(true);

        jRadioButton1_rce.setSelected(true);
        jRadioButton1_rce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_rceActionPerformed(evt);
            }
        });

        jRadioButton_rcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_rcpActionPerformed(evt);
            }
        });

        jRadioButton_rfe.setSelected(true);

        jLabel17.setText("About Us");

        jTextArea_about.setColumns(20);
        jTextArea_about.setRows(5);
        jScrollPane2.setViewportView(jTextArea_about);

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });

        jButton_logout1.setText("LogOut");
        jButton_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_sl)
                                    .addComponent(jRadioButton_yes))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_no)
                                    .addComponent(jRadioButton_fr)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton_2to4)
                                            .addComponent(jLabel9)
                                            .addComponent(jRadioButton_fse)
                                            .addComponent(jRadioButton_oce)
                                            .addComponent(jRadioButton1_rce)
                                            .addComponent(jRadioButton_rfe)
                                            .addComponent(jRadioButton_ore))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(jRadioButton_5ormore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButton_fsg)
                                            .addComponent(jRadioButton_ocg)
                                            .addComponent(jRadioButton_rcg)
                                            .addComponent(jRadioButton_rfg)
                                            .addComponent(jRadioButton_org)
                                            .addComponent(jButton_logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_onlyone))
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jRadioButton_fsf)
                            .addComponent(jRadioButton_ocf)
                            .addComponent(jRadioButton_rcf)
                            .addComponent(jRadioButton_rff)
                            .addComponent(jRadioButton_orf))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonfsp)
                            .addComponent(jLabel12)
                            .addComponent(jRadioButton_ocp)
                            .addComponent(jRadioButton_rcp)
                            .addComponent(jRadioButton_rfp)
                            .addComponent(jRadioButton_orp)))
                    .addComponent(jButton_submite, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_submite, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton_sl)
                                        .addComponent(jRadioButton_fr))
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton_yes)
                            .addComponent(jRadioButton_no))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_2to4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jRadioButton_onlyone)
                                .addComponent(jRadioButton_5ormore)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton_fse)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jRadioButton_oce)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_fsg)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_ocg)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton_rcg)
                                            .addComponent(jRadioButton1_rce)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_fsf)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_ocf))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonfsp)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_ocp)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_rcf)
                                    .addComponent(jRadioButton_rcp))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_rfe)
                            .addComponent(jLabel16)
                            .addComponent(jRadioButton_rfp)
                            .addComponent(jRadioButton_rff)
                            .addComponent(jRadioButton_rfg))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_org)
                                    .addComponent(jRadioButton_orf)
                                    .addComponent(jRadioButton_orp)
                                    .addComponent(jRadioButton_ore))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_slActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_slActionPerformed

    private void jRadioButton_frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_frActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_frActionPerformed

    private void jRadioButton_rcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_rcpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_rcpActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jRadioButton_5ormoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_5ormoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_5ormoreActionPerformed

    private void jButton_submiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submiteActionPerformed
        String name = jTextField_name.getText();
        String slorfr = "Sri Lankan";
        String yesorno = "yes";
        String hlsot = "Only One";
        String osb = "Excelent";
        String oc = "Excelent";
        String cr = "Excelent";
        String rf = "Excelent";
        String or = "Excelent";
        String about = jTextArea_about.getText();

        
        if(jRadioButton_fr.isSelected()){
            slorfr = "Foreigner";
        }
        if(jRadioButton_no.isSelected()){
            yesorno = "No";
        }
        
        if(jRadioButton_2to4.isSelected()){
            hlsot = "2 To 4";
        }
        
        if(jRadioButton_5ormore.isSelected()){
            hlsot = "5 Or More";
        }
        
        if(jRadioButton_fsg.isSelected()){
            osb = "good";
        }
        
        if(jRadioButton_fsf.isSelected()){
            osb = "Fair";
        }
        
        if(jRadioButton_ocg.isSelected()){
            oc = "Good";
        }
        
        if(jRadioButton_ocf.isSelected()){
            oc = "Fair";
        }
        
        if(jRadioButton_ocp.isSelected()){
            oc = "Poor";
        }
        
        if(jRadioButtonfsp.isSelected()){
            osb = "Poor";
        }
        
        if(jRadioButton_rcg.isSelected()){
            cr = "Good";
        }
        
        if(jRadioButton_rcf.isSelected()){
            cr = "Fair";
        }
        
        if(jRadioButton_rcp.isSelected()){
            cr = "Poor";
        }
        
        if(jRadioButton_rfg.isSelected()){
            rf = "Good";
        }
        
        if(jRadioButton_rff.isSelected()){
            rf = "Fair";
        }
        
        if(jRadioButton_rfp.isSelected()){
            rf = "Poor";
        }
        
        if(jRadioButton_org.isSelected()){
            or = "Good";
        }
        
        if(jRadioButton_orf.isSelected()){
            or = "Fair";
        }
        
        if(jRadioButton_orp.isSelected()){
            or = "Poor";
        }
        
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `rating`(`name`, `slorfr`, `firstornot`, `stayourhotel`, `officestaffbehare`, `overrollcleanhotel`, `roomclean`, `resturantfood`, `overroolrating`, `about`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                
                try {
                    
                    ps = my_con.getConnection().prepareStatement(registerUserQuery);
                    
                    ps.setString(1, name);
                    ps.setString(2, slorfr);
                    ps.setString(3, yesorno);
                    ps.setString(4, hlsot);
                    ps.setString(5, osb);
                    ps.setString(6, oc);
                    ps.setString(7, cr);
                    ps.setString(8, rf);
                    ps.setString(9, or);
                    ps.setString(10, about);
                    System.out.println(ps.toString());
                    
                    if(ps.executeUpdate() !=0){
                        JOptionPane.showMessageDialog(null, "You Rated Succesfuly Thank you ","Sucsesfuly",1);
                        }
                    else{
                        JOptionPane.showMessageDialog(null, "Error", "Your Rated Faild", 2);
                    }
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
                }
            
    }//GEN-LAST:event_jButton_submiteActionPerformed

    private void jRadioButton1_rceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_rceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1_rceActionPerformed

    private void jRadioButton_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_yesActionPerformed

    private void jButton_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logout1ActionPerformed
            JOptionPane.showMessageDialog(null, "Are You Sure To LogOut?","Log_Out",2);
            Login_form lf = new Login_form();
            lf.setVisible(true);
            lf.pack();
            lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);    
            this.dispose();
    }//GEN-LAST:event_jButton_logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quality_assurance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quality_assurance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quality_assurance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quality_assurance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quality_assurance_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_logout1;
    private javax.swing.JButton jButton_submite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1_rce;
    private javax.swing.JRadioButton jRadioButton_2to4;
    private javax.swing.JRadioButton jRadioButton_5ormore;
    private javax.swing.JRadioButton jRadioButton_fr;
    private javax.swing.JRadioButton jRadioButton_fse;
    private javax.swing.JRadioButton jRadioButton_fsf;
    private javax.swing.JRadioButton jRadioButton_fsg;
    private javax.swing.JRadioButton jRadioButton_no;
    private javax.swing.JRadioButton jRadioButton_oce;
    private javax.swing.JRadioButton jRadioButton_ocf;
    private javax.swing.JRadioButton jRadioButton_ocg;
    private javax.swing.JRadioButton jRadioButton_ocp;
    private javax.swing.JRadioButton jRadioButton_onlyone;
    private javax.swing.JRadioButton jRadioButton_ore;
    private javax.swing.JRadioButton jRadioButton_orf;
    private javax.swing.JRadioButton jRadioButton_org;
    private javax.swing.JRadioButton jRadioButton_orp;
    private javax.swing.JRadioButton jRadioButton_rcf;
    private javax.swing.JRadioButton jRadioButton_rcg;
    private javax.swing.JRadioButton jRadioButton_rcp;
    private javax.swing.JRadioButton jRadioButton_rfe;
    private javax.swing.JRadioButton jRadioButton_rff;
    private javax.swing.JRadioButton jRadioButton_rfg;
    private javax.swing.JRadioButton jRadioButton_rfp;
    private javax.swing.JRadioButton jRadioButton_sl;
    private javax.swing.JRadioButton jRadioButton_yes;
    private javax.swing.JRadioButton jRadioButtonfsp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_about;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
